// File: components/Mindmap/mockData.ts
// Mock data for mindmap visualization - will be replaced with API data in Phase 6

import type { Project } from '../../types';
import { Quarter } from '../../types';

export const mockProjectData: Project = {
    id: 1,
    type: 'Project',
    title: 'Digital Transformation 2026',
    description: 'Company-wide digital transformation initiative',
    progress: 45,
    isActive: true,
    createdBy: 'admin',
    createdDate: '2025-01-01T00:00:00Z',
    updatedBy: 'admin',
    updatedDate: '2026-02-01T00:00:00Z',
    initiatives: [
        {
            id: 101,
            type: 'StrategicInitiative',
            projectId: 1,
            title: 'Customer Experience',
            description: 'Improve customer touchpoints',
            progress: 60,
            isActive: true,
            createdBy: 'admin',
            createdDate: '2025-01-15T00:00:00Z',
            updatedBy: 'admin',
            updatedDate: '2026-01-20T00:00:00Z',
            goals: [
                {
                    id: 1001,
                    type: 'Goal',
                    strategicInitiativeId: 101,
                    title: 'Mobile App Launch',
                    description: 'Launch new mobile application',
                    progress: 75,
                    isActive: true,
                    createdBy: 'admin',
                    createdDate: '2025-02-01T00:00:00Z',
                    updatedBy: 'admin',
                    updatedDate: '2026-01-15T00:00:00Z',
                    objectives: [
                        {
                            id: 10001,
                            type: 'Objective',
                            goalId: 1001,
                            title: 'Complete UI/UX Design',
                            description: 'Finalize all screens',
                            progress: 100,
                            assignee: 'john.doe',
                            year: 2026,
                            quarter: Quarter.Q1,
                            dueDate: '2026-03-31',
                            isArchived: false,
                            isActive: true,
                            createdBy: 'admin',
                            createdDate: '2025-03-01T00:00:00Z',
                            updatedBy: 'admin',
                            updatedDate: '2026-01-10T00:00:00Z',
                            keyResults: [
                                {
                                    id: 100001,
                                    type: 'KeyResult',
                                    objectiveId: 10001,
                                    title: 'Design 20 screens',
                                    description: 'All app screens designed',
                                    progress: 100,
                                    assignee: 'jane.doe',
                                    dueDate: '2026-03-15',
                                    isActive: true,
                                    createdBy: 'admin',
                                    createdDate: '2025-03-15T00:00:00Z',
                                    updatedBy: 'admin',
                                    updatedDate: '2026-01-05T00:00:00Z',
                                    actionItems: [
                                        {
                                            id: 1000001,
                                            type: 'ActionItem',
                                            keyResultId: 100001,
                                            title: 'Create wireframes',
                                            progress: 100,
                                            dueDate: '2025-04-15',
                                            assignee: 'jane.doe',
                                            isCompleted: true,
                                            isActive: true,
                                            createdBy: 'admin',
                                            createdDate: '2025-03-20T00:00:00Z',
                                            updatedBy: 'admin',
                                            updatedDate: '2025-04-10T00:00:00Z',
                                        },
                                    ],
                                },
                            ],
                        },
                        {
                            id: 10002,
                            type: 'Objective',
                            goalId: 1001,
                            title: 'Backend API Development',
                            description: 'Build REST APIs',
                            progress: 50,
                            assignee: 'bob.smith',
                            year: 2026,
                            quarter: Quarter.Q1,
                            dueDate: '2026-03-31',
                            isArchived: false,
                            isActive: true,
                            createdBy: 'admin',
                            createdDate: '2025-03-01T00:00:00Z',
                            updatedBy: 'admin',
                            updatedDate: '2026-02-01T00:00:00Z',
                            keyResults: [],
                        },
                    ],
                },
                {
                    id: 1002,
                    type: 'Goal',
                    strategicInitiativeId: 101,
                    title: 'Customer Portal Redesign',
                    description: 'Modernize the customer portal',
                    progress: 45,
                    isActive: true,
                    createdBy: 'admin',
                    createdDate: '2025-02-15T00:00:00Z',
                    updatedBy: 'admin',
                    updatedDate: '2026-01-20T00:00:00Z',
                    objectives: [],
                },
            ],
        },
        {
            id: 102,
            type: 'StrategicInitiative',
            projectId: 1,
            title: 'Operational Efficiency',
            description: 'Streamline internal processes',
            progress: 30,
            isActive: true,
            createdBy: 'admin',
            createdDate: '2025-01-20T00:00:00Z',
            updatedBy: 'admin',
            updatedDate: '2026-01-25T00:00:00Z',
            goals: [
                {
                    id: 1003,
                    type: 'Goal',
                    strategicInitiativeId: 102,
                    title: 'Automate Reporting',
                    description: 'Implement automated reports',
                    progress: 30,
                    isActive: true,
                    createdBy: 'admin',
                    createdDate: '2025-03-01T00:00:00Z',
                    updatedBy: 'admin',
                    updatedDate: '2026-01-18T00:00:00Z',
                    objectives: [],
                },
            ],
        },
        {
            id: 103,
            type: 'StrategicInitiative',
            projectId: 1,
            title: 'Data Analytics Platform',
            description: 'Build analytics capabilities',
            progress: 20,
            isActive: true,
            createdBy: 'admin',
            createdDate: '2025-02-01T00:00:00Z',
            updatedBy: 'admin',
            updatedDate: '2026-02-01T00:00:00Z',
            goals: [],
        },
    ],
};
